name: 'Install NSIS'
description: 'Installs NSIS including the EnvVar plugin (only supported on Windows)'
author: 'repolevedavaj'
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'dist/index.js'
